### ISSUE TITLE
A question about finetune the autoencoder

### ISSUE THREAD

**Issue by RunpuWei** [nickyisadog/latent-diffusion-inpainting#14]
Hello author, thank you for such a perfect job! Now I want to use your code to do inpainting of colonoscopy polyps. 

I would like to ask a question of step 1 (Finetune the autoencoder), I don't seem to find the code related to stopping training in the code, is your code also not automatically stopping training? If yes, how many epoch or iteration did you finetune on the colonoscopy polyp dataset?

Looking forward to your reply!

**Comment by Polaris0421** [comment]
hi, have you figured out the question? I try to find the code setting up the number of epochs but I fail

**Comment by ultiwinter** [comment]
@RunpuWei Hi, thanks for putting the question out there, would you mind sharing your solution you found?

**Comment by Coder-li-jiahao** [comment]
Encountered the same problem, looking forward to a reply
