### ISSUE TITLE
weight of size [256, 7, 3, 3], expected input[1, 6, 128, 128] to have 7 channels

### ISSUE THREAD

**Issue by dov84d** [nickyisadog/latent-diffusion-inpainting#2]
Thanks for the training code!

I fixed the errors in the issues "KeyError 'global_step'", and then I encounter the following error:
RuntimeError: Given groups=1, weight of size [256, 7, 3, 3], expected input[1, 6, 128, 128] to have 7 channels, but got 6 channels instead

I am using your data and I am not sure what is the reason.
Can you please assist?

**Comment by nickyisadog** [comment]
Is this for autoencoder ??

**Comment by dov84d** [comment]
Nope, 
It's happened when I try to fine tune the latent diffusion model here:
https://github.com/nickyisadog/latent-diffusion-inpainting#3-finetune-latent-diffusion-model

**Comment by dov84d** [comment]
I found the issue,

It's seems that ddpm.py was import somehow from anther directory.
Thanks for the help.
