### ISSUE TITLE
Error(s) in loading state_dict for LatentDiffusion

### ISSUE THREAD

**Issue by garfieldtong** [nickyisadog/latent-diffusion-inpainting#5]
When i finetune in step3,

Error(s) in loading state_dict for LatentDiffusion:Unexpected key(s) in state_dict: "ddim_sigmas", "ddim_alphas", "ddim_alphas_prev", "ddim_sqrt_one_minus_alphas".

Any thoughts?

**Comment by nickyisadog** [comment]
> When i finetune in step3,
> 
> Error(s) in loading state_dict for LatentDiffusion:Unexpected key(s) in state_dict: "ddim_sigmas", "ddim_alphas", "ddim_alphas_prev", "ddim_sqrt_one_minus_alphas".
> 
> Any thoughts?

Solved in #1
