### ISSUE TITLE
segmentation fault (core dumped) 错误

### ISSUE THREAD

**Issue by Jia7878** [nickyisadog/latent-diffusion-inpainting#6]
hello,I was interested about your great work,but I was confused by this error:"segmentation fault (core dumped) "when epoch 1 just start.could you have some methods?

**Comment by nickyisadog** [comment]
https://github.com/CompVis/latent-diffusion/issues/119

**Comment by Jia7878** [comment]
> [CompVis/latent-diffusion#119](https://github.com/CompVis/latent-diffusion/issues/119)

Thank you for you reply, but I have tried to change order of "import scann" and environment,which is not working.
Moreover,my subject is also generate polyps in endoscope. Could I have your Wechat for communication?

**Comment by nickyisadog** [comment]
wehat:CTHhaha

> > [CompVis/latent-diffusion#119](https://github.com/CompVis/latent-diffusion/issues/119)
> 
> Thank you for you reply, but I have tried to change order of "import scann" and environment,which is not working. Moreover,my subject is also generate polyps in endoscope. Could I have your Wechat for communication?

wehat:CTHhaha

**Comment by nickyisadog** [comment]
downgrade to CUDA 11.6
